compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: 0

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - arm64
    - x64
  libc:
    - glibc
    - musl
  os:
    - linux

yarnPath: .yarn/releases/yarn-4.9.0.cjs
