compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: 0

supportedArchitectures:
  cpu:
    - arm64
    - x64
  libc:
    - glibc
    - musl
  os:
    - linux

yarnPath: .yarn/releases/yarn-4.0.0-rc.51.cjs
