version: '3.8'

services:
  # mariadb:
  #   image: mariadb:10.2
  #   environment:
  #     MYSQL_ROOT_PASSWORD: test
  #     MYSQL_DATABASE: test
  #   ports:
  #     - 3306:3306
  #   logging:
  #     options:
  #       max-size: 50k
  #       max-file: '1'
  #   restart: 'unless-stopped'

  project:
    image: node:14
    command: sleep infinity
    environment:
      TZ: Europe/Paris
    ports:
      - 3000:3000
    working_dir: /workspace
    volumes:
      - .:/workspace
    logging:
      options:
        max-size: 50k
        max-file: '1'
    restart: 'no'
