services:
  mariadb:
    image: mariadb:11.4
    command: --skip-bind-address
    environment:
      MARIADB_ROOT_PASSWORD: my_root_password_for_local
    logging:
      options:
        max-size: 50k
        max-file: '1'
    restart: 'unless-stopped'

  project:
    image: node:22
    command: sleep infinity
    environment:
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
      MARIADB_ROOT_PASSWORD: my_root_password_for_local

      TZ: Europe/Paris

      NODE_NO_WARNINGS: 1
    ports:
      - 3000:3000
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ~/.bash_history:/root/.ash_history
      - ~/.bash_history:/root/.bash_history
    depends_on:
      - mariadb
    logging:
      options:
        max-size: 50k
        max-file: '1'
    restart: 'no'
