version: '3.8'

services:
  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
    logging:
      options:
        max-size: 50k
        max-file: '1'
    restart: 'unless-stopped'

  project:
    image: node:14
    command: sleep infinity
    depends_on:
      - mariadb
    environment:
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
      MARIADB_USER: root
      MARIADB_PASSWORD: test
      MARIADB_DATABASE: test

      TZ: Europe/Paris
    ports:
      - 3000:3000
      - 9222:9222
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ~/.bash_history:/root/.bash_history
    logging:
      options:
        max-size: 50k
        max-file: '1'
    restart: 'no'
