version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    command: --skip-bind-address
    environment:
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: test
    ports:
      - 3306:3306
    logging:
      options:
        max-size: 50k
        max-file: '1'
    restart: 'unless-stopped'

  project:
    image: node:18
    command: sleep infinity
    environment:
      TZ: Europe/Paris
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ~/.bash_history:/root/.bash_history
      - ~/.bash_history:/root/.ash_history
    depends_on:
      - mariadb
    logging:
      options:
        max-size: 50k
        max-file: '1'
    restart: 'no'
