name: CI

on: [push, pull_request]

jobs:
  setup-build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 14
          # - 15

        package:
          - graphql-platform
          - graphql-platform-scalars
          - graphql-platform-utils

    steps:
      - name: Setup NodeJS v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Validate the "${{ matrix.package }}" package's dependencies
        run: yarn install --immutable --immutable-cache

      - name: Build "${{ matrix.package }}"
        run: yarn build
        working-directory: packages/${{ matrix.package }}

      - name: Test "${{ matrix.package }}"
        run: yarn test --ci
        working-directory: packages/${{ matrix.package }}
