name: CI

on: [push, pull_request]

jobs:
  setup-build-and-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        node:
          - 18

        include:
          - node: 18
            publish: true
            continue-on-error: false

    continue-on-error: ${{ matrix.continue-on-error == true }}

    container:
      image: node:${{ matrix.node }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install the dependencies
        run: yarn install --immutable

      - name: Compile the code
        run: yarn run compile

      - name: Test
        run: yarn run test
