name: CI

on: [push, pull_request]

jobs:
  setup-build-and-test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: bitnami/mariadb:10.6
        env:
          MARIADB_ROOT_PASSWORD: my_root_password_for_tests
        ports: ['3306:3306']
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: false

      matrix:
        node:
          - 16
          - 18

        include:
          - node: 16
            publish: true
            continue-on-error: false

    continue-on-error: ${{ matrix.continue-on-error == true }}

    container:
      image: node:${{ matrix.node }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install the dependencies
        run: yarn install --immutable

      - name: Compile the code
        run: yarn run compile

      - name: Test
        run: yarn run test
        env:
          MARIADB_HOST: mariadb
          MARIADB_PORT: 3306
          MARIADB_ROOT_PASSWORD: my_root_password_for_tests

      - name: Publish to npmjs
        if: "matrix.publish == true && startsWith(github.ref, 'refs/tags/')"
        run: |
          yarn workspaces foreach --all --no-private npm publish --tolerate-republish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_AUTH_TOKEN }}
